# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TAL.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 673)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("font: 75 13pt \"Bitstream Charter\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(150, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(100, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 3, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"font: bold 15pt \"Abyssinica SIL\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("font: 75 11pt \"Bitstream Charter\";\n"
"font: 75 11pt \"Bitstream Charter\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setMinimumSize(QtCore.QSize(300, 40))
        self.textEdit_2.setMaximumSize(QtCore.QSize(400, 40))
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setStyleSheet("font: 75 11pt \"Bitstream Charter\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.textEdit.setMaximumSize(QtCore.QSize(400, 40))
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(100, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.tab_4)
        self.treeView.setObjectName("treeView")
        self.gridLayout_6.addWidget(self.treeView, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.tab_4)
        self.listView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.listView.setAutoFillBackground(True)
        self.listView.setStyleSheet("\n"
"font: 75 11pt \"Bitstream Charter\";\n"
"")
        self.listView.setObjectName("listView")
        self.gridLayout_6.addWidget(self.listView, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.toolBox = QtWidgets.QToolBox(self.tab_5)
        self.toolBox.setGeometry(QtCore.QRect(18, 110, 781, 356))
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 426, 164))
        self.page.setMouseTracking(False)
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.insertmeaning = QtWidgets.QPushButton(self.page)
        self.insertmeaning.setMinimumSize(QtCore.QSize(100, 40))
        self.insertmeaning.setMaximumSize(QtCore.QSize(16777215, 40))
        self.insertmeaning.setObjectName("insertmeaning")
        self.horizontalLayout_8.addWidget(self.insertmeaning)
        self.editmeaning = QtWidgets.QLineEdit(self.page)
        self.editmeaning.setMinimumSize(QtCore.QSize(300, 40))
        self.editmeaning.setMaximumSize(QtCore.QSize(16777215, 40))
        self.editmeaning.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editmeaning.setText("")
        self.editmeaning.setObjectName("editmeaning")
        self.horizontalLayout_8.addWidget(self.editmeaning)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.listmeaning = QtWidgets.QTableWidget(self.page)
        self.listmeaning.setObjectName("listmeaning")
        self.listmeaning.setColumnCount(0)
        self.listmeaning.setRowCount(0)
        self.listmeaning.horizontalHeader().setStretchLastSection(True)
        self.listmeaning.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.listmeaning)
        self.toolBox.addItem(self.page, "")
        self.Examples = QtWidgets.QWidget()
        self.Examples.setGeometry(QtCore.QRect(0, 0, 781, 276))
        self.Examples.setObjectName("Examples")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Examples)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.insertexample = QtWidgets.QPushButton(self.Examples)
        self.insertexample.setMinimumSize(QtCore.QSize(100, 40))
        self.insertexample.setMaximumSize(QtCore.QSize(16777215, 40))
        self.insertexample.setObjectName("insertexample")
        self.horizontalLayout_9.addWidget(self.insertexample)
        self.modifyexample = QtWidgets.QLineEdit(self.Examples)
        self.modifyexample.setMinimumSize(QtCore.QSize(300, 40))
        self.modifyexample.setMaximumSize(QtCore.QSize(16777215, 40))
        self.modifyexample.setObjectName("modifyexample")
        self.horizontalLayout_9.addWidget(self.modifyexample)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.label_4 = QtWidgets.QLabel(self.Examples)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.exampleslist = QtWidgets.QTableWidget(self.Examples)
        self.exampleslist.setMinimumSize(QtCore.QSize(300, 0))
        self.exampleslist.setObjectName("exampleslist")
        self.exampleslist.setColumnCount(0)
        self.exampleslist.setRowCount(0)
        self.exampleslist.horizontalHeader().setStretchLastSection(True)
        self.exampleslist.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.exampleslist)
        self.toolBox.addItem(self.Examples, "")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(10, 490, 791, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(18, 510, 401, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_19.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_19.addWidget(self.pushButton_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(18, 20, 778, 70))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.wordtext = QtWidgets.QTextEdit(self.layoutWidget1)
        self.wordtext.setMinimumSize(QtCore.QSize(300, 40))
        self.wordtext.setMaximumSize(QtCore.QSize(400, 40))
        self.wordtext.setOverwriteMode(False)
        self.wordtext.setObjectName("wordtext")
        self.verticalLayout.addWidget(self.wordtext)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.period = QtWidgets.QComboBox(self.layoutWidget1)
        self.period.setMinimumSize(QtCore.QSize(200, 30))
        self.period.setMaximumSize(QtCore.QSize(250, 30))
        self.period.setObjectName("period")
        self.verticalLayout_6.addWidget(self.period)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.genre = QtWidgets.QComboBox(self.layoutWidget1)
        self.genre.setMinimumSize(QtCore.QSize(150, 30))
        self.genre.setMaximumSize(QtCore.QSize(200, 30))
        self.genre.setObjectName("genre")
        self.verticalLayout_7.addWidget(self.genre)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.checkword = QtWidgets.QPushButton(self.layoutWidget1)
        self.checkword.setMinimumSize(QtCore.QSize(100, 30))
        self.checkword.setMaximumSize(QtCore.QSize(100, 30))
        self.checkword.setObjectName("checkword")
        self.horizontalLayout_2.addWidget(self.checkword)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.wordlabel = QtWidgets.QLabel(self.tab)
        self.wordlabel.setObjectName("wordlabel")
        self.horizontalLayout_7.addWidget(self.wordlabel)
        self.word_stat = QtWidgets.QLineEdit(self.tab)
        self.word_stat.setObjectName("word_stat")
        self.horizontalLayout_7.addWidget(self.word_stat)
        self.Lookstat = QtWidgets.QRadioButton(self.tab)
        self.Lookstat.setObjectName("Lookstat")
        self.horizontalLayout_7.addWidget(self.Lookstat)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.barchartGenre = QtWidgets.QLabel(self.tab)
        self.barchartGenre.setText("")
        self.barchartGenre.setObjectName("barchartGenre")
        self.gridLayout_2.addWidget(self.barchartGenre, 0, 1, 1, 1)
        self.barchartPeriod = QtWidgets.QLabel(self.tab)
        self.barchartPeriod.setText("")
        self.barchartPeriod.setObjectName("barchartPeriod")
        self.gridLayout_2.addWidget(self.barchartPeriod, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionquit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionquit.setFont(font)
        self.actionquit.setObjectName("actionquit")
        self.menu.addAction(self.actionquit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", " تسجيل الدخول "))
        self.label.setText(_translate("MainWindow", "مؤلف المعجم"))
        self.label_2.setText(_translate("MainWindow", "كلمة السر"))
        self.pushButton.setText(_translate("MainWindow", "تسجيل الدخول"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "صحة المستندات"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "توليد القاموس"))
        self.label_8.setText(_translate("MainWindow", "هيكل محتويات كوربوس العربية"))
        self.label_9.setText(_translate("MainWindow", "محتوى الملف المختار"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "تصور"))
        self.insertmeaning.setText(_translate("MainWindow", "إضافة"))
        self.label_5.setText(_translate("MainWindow", "معنى"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", " المعاني"))
        self.insertexample.setText(_translate("MainWindow", "إضافة"))
        self.label_4.setText(_translate("MainWindow", "أمثلة ( مرتبة  وفقا لمدى الصلة)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Examples), _translate("MainWindow", "أمثلة"))
        self.pushButton_5.setText(_translate("MainWindow", "إلغاء"))
        self.pushButton_4.setText(_translate("MainWindow", "تأكيد"))
        self.label_3.setText(_translate("MainWindow", "كلمة"))
        self.label_6.setText(_translate("MainWindow", "العصر:"))
        self.label_7.setText(_translate("MainWindow", "صنف:"))
        self.checkword.setText(_translate("MainWindow", "فحص"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "مؤلف المعجم   "))
        self.wordlabel.setText(_translate("MainWindow", "كلمة"))
        self.Lookstat.setText(_translate("MainWindow", "ابدا البحث"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "إحصائيات"))
        self.menu.setTitle(_translate("MainWindow", "قائمة التطبيق"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionquit.setText(_translate("MainWindow", "&quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

